### ISSUE TITLE
Erase tact-template Git history

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/jetton#4]
It's not relevant for this project. Let's do it asap

**Comment by Shvandre** [comment]
Fixed.

**Comment by anton-trunov** [comment]
not yet

<img width="452" alt="image" src="https://github.com/user-attachments/assets/b77d7bae-2ceb-42f5-9648-75fa1fa1513a">

**Comment by Shvandre** [comment]
Lol, maybe list of Contributors on the main page will be updated soon. 
![image](https://github.com/user-attachments/assets/5762d7b7-7ad1-48ac-9921-c9cd10ba0611)
(That is what i see after clicking on contributors)

**Comment by anton-trunov** [comment]
after you fix this, I'll disable force pushes to `main`

**Comment by Shvandre** [comment]
> no, `git log` in the command line does show authors other than you

I think not it is Done
