### ISSUE TITLE
Possible bug in `bounced<TokenTransferInternal>` receiver

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/jetton#7]
Duplicate `self.balance`reference:

https://github.com/tact-lang/jetton/blob/543803a2929929bc7fe2c9d93e3454745bebd401/sources/jetton_wallet.tact#L139

```tact
bounced(msg: bounced<TokenTransferInternal>){
    self.balance += self.balance + msg.amount;
}
```

Pointed out by Alexey Malanov.

**Comment by Shvandre** [comment]
Oh, you are 100% right, serious typo.

**Comment by anton-trunov** [comment]
> Oh, you are 100% right, serious typo.

which shows we need to increase test coverage
